import { Container } from "@/components/containers/Container";
import { ContentText, ContentImage, ContentGrid } from "@/components/containers/Contents";
import { Section } from "@/components/containers/Section";
import { WrapperButton, WrapperCommunicatory } from "@/components/containers/Wrapper";
import { Caption } from "@/components/typography/Caption";
import { Headline } from "@/components/typography/Headline";
import { Paragraph } from "@/components/typography/Paragraph";
import { Button } from "@/components/ui/Button";
import { Communicatory } from "@/components/ui/Communicatory";
import { ArchiveIcon } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Desginer System",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="">
      
    <Section background="dark" paddingY="true" height="full">
      <Container>

        <ContentText alignItemX="lgStart" padding="true">
          <Caption>Componente Caption</Caption>
          <Headline alignText="lgStart" color="light" heading="h1">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit, laborum nisi <span className="text-primary-blue">componente headline</span> </Headline>
          <Paragraph alignText="lgStart" color="light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsum odio optio rem, ducimus natus veniam officia magnam quidem, delectus, nobis nam quam cupiditate voluptatem sed aliquam ratione consequuntur amet?</Paragraph>

          <WrapperButton>
            <Button>Assine agora</Button>
            <Button style="weak">Conheça nossos planos</Button>
          </WrapperButton>
        </ContentText>

        <ContentImage alignItemY="center" padding="true">
          <p className="text-white bg-neutral-700 w-full h-full flex items-center justify-center rounded-lg">Content Imagem</p>
        </ContentImage>

      </Container>
    </Section>

    <Section background="dark" paddingY="true" height="full">
      <Container>

        <ContentText alignItemX="lgStart" padding="true" className="order-2">
          <ContentText alignItemX="lgStart" padding="true">
            <Caption>Componente Caption</Caption>
            <Headline alignText="lgStart" color="light">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</Headline>
            <Paragraph alignText="lgStart" color="light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsum odio optio rem, ducimus natus veniam officia magnam.</Paragraph>

            <WrapperCommunicatory>
              <Communicatory 
                styleType="complete"
                colorHeadline="white"
                colorParagraph="white"
                headline={'consectetur adipisicing elit.'} 
                subHeadline={'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsum odio optio rem, ducimus natus veniam officia magnam.'}
              >
                <ArchiveIcon color="#3F8CFF" size={'26px'} strokeWidth={'1.5'} />
              </Communicatory>

              <Communicatory 
                styleType="complete"
                colorHeadline="white"
                colorParagraph="white"
                headline={'consectetur adipisicing elit.'} 
                subHeadline={'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsum odio optio rem, ducimus natus veniam officia magnam.'}
              >
                <ArchiveIcon color="#3F8CFF" size={'26px'} strokeWidth={'1.5'} />
              </Communicatory>
            </WrapperCommunicatory>

            <WrapperButton>
              <Button>Assine agora</Button>
              <Button style="weak">Conheça nossos planos</Button>
            </WrapperButton>

          </ContentText>
        </ContentText>

        <ContentGrid className="order-1" >
          <p className="text-white bg-neutral-700 w-full py-20 col-span-6 rounded-lg">Content Grid</p>
          <p className="text-white bg-neutral-700 w-full py-20 col-span-6 rounded-lg">Content Grid</p>
          <p className="text-white bg-neutral-700 w-full py-20 col-span-12 rounded-lg">Content Grid</p>
        </ContentGrid>

      </Container>
    </Section>

    </main>
  )
}
