import { Container } from "@/components/containers/Container";
import { ContentGrid, ContentText } from "@/components/containers/Contents";
import { Section } from "@/components/containers/Section";
import { WrapperButton } from "@/components/containers/Wrapper";
import { Button } from "@/components/interface/Button";
import { Caption } from "@/components/typography/Caption";
import { Headline } from "@/components/typography/Headline";
import { Paragraph } from "@/components/typography/Paragraph";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Designer Test",
  description: "Generated by create next app",
};

export default function Home(){
  return(
    <main>

    <Section height="full" background="darkTheme1" paddingY="true" className="pt-28">
      <Container background="darkTheme2" className="rounded-lg">

        <ContentText background="darkTheme3" className="rounded-lg" padding="true">
          <Headline color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        </ContentText>

        <ContentGrid padding="true" background="darkTheme3" className="rounded-lg">
          <div className="bg-dark-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="darkTheme1" paddingY="true">
      <Container background="darkTheme2" className="rounded-lg">

        <ContentText background="darkTheme3" padding="true" alignItemX="lgStart" className="rounded-lg order-2"> 
          <Caption style="darkSolid">Lorem ipsum dolor sit</Caption>
          <Headline color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        
          <WrapperButton>
            <Button style="weak">Cadastrar</Button>
            <Button style="weak">Assine Agora</Button>
          </WrapperButton>
        </ContentText>

        <ContentGrid padding="true" background="darkTheme3" className="rounded-lg">
          <div className="bg-dark-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="lightTheme4" paddingY="true">
      <Container background="lightTheme2" className="rounded-lg">

        <ContentText background="lightTheme3" padding="true" alignItemX="lgStart" className="rounded-lg">
          <Caption style="solid">Lorem ipsum dolor sit</Caption>
          <Headline color="mainTextColors3" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors2" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        
          <WrapperButton>
            <Button style="weak">Cadastrar</Button>
            <Button style="textded">Assine Agora</Button>
          </WrapperButton>
        </ContentText>

        <ContentGrid padding="true" background="lightTheme3" className="rounded-lg">
          <div className="bg-light-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-light-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-light-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="lightTheme4" paddingY="true">
      <Container background="lightTheme2" className="rounded-lg">

        <ContentText background="lightTheme3" padding="true" alignItemX="lgStart" className="rounded-lg">
          <Caption style="solid">Lorem ipsum dolor sit</Caption>
          <Headline color="mainTextColors3" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors2" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        
          <WrapperButton>
            <Button style="weak">Cadastrar</Button>
            <Button style="textded">Assine Agora</Button>
          </WrapperButton>
        </ContentText>

      </Container>
    </Section>

    </main>
  )
}