import { Container } from "@/components/containers/Container";
import { ContentGrid, ContentText } from "@/components/containers/Contents";
import { Section } from "@/components/containers/Section";
import { WrapperButton } from "@/components/containers/Wrapper";
import { Button } from "@/components/interface/Button";
import { Caption } from "@/components/typography/Caption";
import { Headline } from "@/components/typography/Headline";
import { Paragraph } from "@/components/typography/Paragraph";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Designer Test",
  description: "Generated by create next app",
};

export default function Home(){
  return(
    <main>

    <Section height="full" background="darkTheme1" paddingY="true" className="pt-28">
      <Container className="rounded-lg">

        <ContentText className="rounded-lg" padding="true">
          <Headline color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        </ContentText>

        <ContentGrid padding="true" background="darkTheme3" className="rounded-lg">
          <div className="bg-dark-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="darkTheme1" paddingY="true">
      <Container  className="rounded-lg">

        <ContentText background="darkTheme3" padding="true" alignItemX="lgStart" className="rounded-lg order-2"> 
          <Headline color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors4" alignText="lgStart" className="bg-dark-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        </ContentText>

        <ContentGrid padding="true" background="darkTheme3" className="rounded-lg">
          <div className="bg-dark-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-dark-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="lightTheme4" paddingY="true">
      <Container  className="rounded-lg">

        <ContentText background="lightTheme3" padding="true" alignItemX="lgStart" className="rounded-lg">
          <Headline color="mainTextColors3" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors2" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        </ContentText>

        <ContentGrid padding="true" background="lightTheme3" className="rounded-lg">
          <div className="bg-light-theme-4 col-span-12 rounded-lg"></div>
          <div className="bg-light-theme-4 col-span-6 rounded-lg"></div>
          <div className="bg-light-theme-4 col-span-6 rounded-lg"></div>
        </ContentGrid>

      </Container>
    </Section>

    <Section height="full" background="lightTheme4" paddingY="true">
      <Container  className="rounded-lg">

        <ContentText background="lightTheme3" padding="true" alignItemX="lgStart" className="rounded-lg">
          <Headline color="mainTextColors3" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat deleniti, rem ullam delectus est </Headline>
          <Paragraph color="mainTextColors2" alignText="lgStart" className="bg-light-theme-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur dolore animi asperiores sunt illo incidunt quod officiis, provident natus iure repellat quasi, possimus aliquam sed, omnis ex repellendus. Sunt, officiis!</Paragraph>
        </ContentText>

      </Container>
    </Section>

    <Section height="full" background="lightTheme4" paddingY="true">
      <Container  className="rounded-lg">

        <ContentText background="lightTheme3" padding="true" alignItemX="allCenter" className="rounded-lg">
          <Button redirect="TesteRedirect" style="emphasis">emphasis</Button>
        </ContentText>

        <ContentText background="lightTheme3" padding="true" alignItemX="allCenter" className="rounded-lg">
          <Caption style="emphasis">Lorem ipsum dolor sit</Caption>
          <Caption style="ligth">Lorem ipsum dolor sit</Caption>
          <Caption style="dark">Lorem ipsum dolor sit</Caption>
          <Caption style="texted">Lorem ipsum dolor sit</Caption>
          <Caption style="ghost">Lorem ipsum dolor sit</Caption>
        </ContentText>

      </Container>
    </Section>

    <Section height="full" background="darkTheme1" paddingY="true">
      <Container className="rounded-lg">

        <ContentText padding="true" alignItemX="allCenter" className="rounded-lg">
          <Caption style="emphasis">Lorem ipsum dolor sit</Caption>
        </ContentText>

        <ContentText padding="true" alignItemX="allCenter" className="rounded-lg">
          <Caption style="emphasis">Lorem ipsum dolor sit</Caption>
          <Caption style="ligth">Lorem ipsum dolor sit</Caption>
          <Caption style="dark">Lorem ipsum dolor sit</Caption>
          <Caption style="texted">Lorem ipsum dolor sit</Caption>
          <Caption style="ghost">Lorem ipsum dolor sit</Caption>
        </ContentText>

      </Container>
    </Section>
    
    </main>
  )
}