import { Container } from "@/components/containers/Container";
import { ContentImage, ContentText } from "@/components/containers/Contents";
import { Section } from "@/components/containers/Section";
import { WrapperButton } from "@/components/containers/Wrapper";
import { Button } from "@/components/interface/Button";
import { Caption } from "@/components/typography/Caption";
import { Headline } from "@/components/typography/Headline";
import { Paragraph } from "@/components/typography/Paragraph";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Link Dedicado",
  description: "Generated by create next app",
};

export default function Home () {
  return(
    <main className="">

      <Section height="full" paddingY="true" className="pt-20"> 
        <Container paddingX="true">

          <ContentText alignItemX="lgStart" padding="true">
            <Caption style="solid">Conheça tudo sobre a Teracorporation</Caption>
            <Headline alignText="lgStart" heading="h1">Link Dedicado</Headline>
            <Paragraph alignText="lgStart">A Teracorporation fornece soluções de internet corporativa escaláveis e estáveis para empresas de todos os tamanhos, com disponibilidade de serviço de 97,5% ou mais. A rede da empresa é construída em topologia de anel, permitindo conexões em dupla abordagem. O sistema de monitoramento NOC monitora a rede em tempo real e fornece gerenciamento proativo 24/7 com alta redundância. A Teracorporation possui licença da Anatel e todos os seus equipamentos são homologados por ela.</Paragraph>
            
            <WrapperButton>
              <Button style="weak">Saiba mais</Button>
              <Button style="outline">Fale com um vendedor</Button>
            </WrapperButton>
          </ContentText>

          <ContentImage background="lightTheme1">
            Content Img
          </ContentImage>

        </Container>
      </Section>

      <Section height="full" paddingY="true"> 
        <Container paddingX="true">

          <ContentText alignItemX="lgStart" className="order-2" padding="true">
            <Caption style="solid">Venha para o futuro da conexão</Caption>
            <Headline alignText="lgStart">A solução de internet corporativa da Teracorporation foi desenvolvida para facilitar a vida de empresas de diferentes portes.</Headline>
            <Paragraph alignText="lgStart">Com topologia inteligente a nossa conexão é totalmente escalável, nossa solução é composta por elementos que garantem a entrega da velocidade necessária para que seu negócio atinja o nível de excelência que almeja.</Paragraph>
            <Paragraph alignText="lgStart">Uma das preocupações da nossa empresa é a satisfação de nossos clientes e para isso focamos entregar uma conexão 100% estável, com disponibilidade de serviço igual, ou maior que 97,5%.</Paragraph>
          </ContentText>

          <ContentImage background="lightTheme1" className="order-1">
            Content Img
          </ContentImage>

        </Container>
      </Section>

      <Section height="full" paddingY="true"> 
        <Container paddingX="true">

          <ContentText alignItemX="lgStart" className="order-1" padding="true">
            <Caption style="solid">Venha para o futuro da conexão</Caption>
            <Paragraph alignText="lgStart">Toda a rede da Teracorporation foi desenvolvida em topologia de anel, o que garante a possibilidade de entregar conexões em dupla abordagem se assim o cliente preferir. Nosso sistema de monitoramento o NOC (Network Operation Center), realiza o monitoramento da nossa rede e de todos os clientes online em tempo real rastreando e prevenindo possíveis falhas em nossa conexão, com um gerenciamento proativo 7x24x365 e redundância de alta capacidade seguindo o protocolo de roteamento dinâmico (BGP4), cliente de link corporativo da Teracorporation pode ficar tranquilo em relação a conexão de sua empres</Paragraph>
            <Paragraph alignText="lgStart">Nossa empresa é detentora da licença SCM da Anatel, assim como, todos os nossos equipamentos também são homologados pela Anatel.</Paragraph>
          </ContentText>

          <ContentImage background="lightTheme1" className="order-2">
            Content Img
          </ContentImage>

        </Container>
      </Section>

      <Section height="full" paddingY="true"> 
        <Container paddingX="true">

          <ContentText alignItemX="lgStart" className="order-2" padding="true">
            <Caption style="solid">Venha para o futuro da conexão</Caption>
            <Headline alignText="lgStart">Veja agora algumas das vantagens de contratar um link dedicado da Teracorporation:</Headline>
            <Paragraph alignText="lgStart">Disponibilidade igual, ou maior que 97,5%;</Paragraph>
            <Paragraph alignText="lgStart">Circuito full-duplex com 100% de banda garantida (mesma velocidade para upload/download);</Paragraph>
            <Paragraph alignText="lgStart">Rede totalmente escalável, pronta para realizar upgrades sempre que necessário;</Paragraph>
            <Paragraph alignText="lgStart">Possibilidade de entrega em dupla abordagem;</Paragraph>
            <Paragraph alignText="lgStart">Rotas internacionais de tráfego;</Paragraph>
            <Paragraph alignText="lgStart">Cabeamento submarino;</Paragraph>
            <Paragraph alignText="lgStart">Presença em um dos principais Data Centers de Miami – EUA;</Paragraph>
            <Paragraph alignText="lgStart">SLA de até 04 horas após abertura de chamado técnico;</Paragraph>
            <Paragraph alignText="lgStart">NOC (premium).</Paragraph>
          </ContentText>

          <ContentImage background="lightTheme1" className="order-1">
            Content Img
          </ContentImage>

        </Container>
      </Section>

    </main>
  )
}