import { Container } from "@/components/containers/Container";
import { ContentText, ContentImage, ContentGrid } from "@/components/containers/Contents";
import { Section } from "@/components/containers/Section";
import { WrapperButton, WrapperCommunicatory } from "@/components/containers/Wrapper";
import { NavigationMenuDemo } from "@/components/navegation/Navegation";
import { Caption } from "@/components/typography/Caption";
import { Headline } from "@/components/typography/Headline";
import { Paragraph } from "@/components/typography/Paragraph";
import { Button } from "@/components/interface/Button";
import { Metadata } from "next";
import { Communicatory } from "@/components/interface/Communicatory";

export const metadata: Metadata = {
  title: "Desginer System",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
    
      <Section height="full" paddingY="true" className="pt-28">
        <Container>

          <div className="col-span-2"></div>

          <ContentText background="featuredTheme1" gridCol="none" className="col-span-8 justify-end rounded-xl" alignItemX="lgStart" padding="true">
            <Caption style="darkSolid">saiba tudo sobre nosso blog pessoal</Caption>
            <Headline alignText="lgStart" heading="h1" color="mainTextColors4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae omnis ut sit.</Headline>
            <Paragraph alignText="lgStart" color="mainTextColors4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. At doloribus sint suscipit provident obcaecati similique deleniti fugiat quasi enim? Iste vero, quasi culpa itaque maxime sapiente! Quos minus doloremque optio!</Paragraph>
          </ContentText>

          <div className="col-span-2"></div>

        </Container>
      </Section>

      

    </main>
  )
}
